### ISSUE TITLE
How to integrate the Telescope?

### ISSUE THREAD

**Issue by tboqi** [TypiCMS/Base#156]
I  integrated the Telescope, but the url "/telescope" redirect to "en/telescope".
how can I setting it?

**Comment by codivist** [comment]
are you using the other languages in your site or just en? i.e. `fr/contact` 

If you're only using english, you can uncheck the `FR` and `NL` language options and then it should work fine.
If not you can try setting up a custom route for it

**Comment by sdebacker** [comment]
Here is how to do it:

1. In `/app/Http/Kernel.php`, add `'setLocale' => \TypiCMS\Modules\Core\Http\Middleware\SetLocale::class,` in the `$routeMiddleware` array.

2. Remove `\TypiCMS\Modules\Core\Http\Middleware\SetLocale::class,` from the web middleware group.

3. Add 'setLocale' in the public and admin middleware groups.

4. Publish the Users module and in the `RouteServiceProvider`, add the `setLocale` middleware like this: `$router->middleware('web', 'setLocale')`.

This will be fixed in the next release of TypiCMS.
